# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
      - image: circleci/node:7.10

      # Specify service dependencies here if necessary
      # CircleCI maintains a library of pre-built images
      # documented at https://circleci.com/docs/2.0/circleci-images/
      # - image: circleci/mongo:3.4.4

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # run tests!
#      - run: yarn test

      # build project
      - run: sudo npm install -g bower grunt-cli yo install bower and grunt
      - run: sudo npm install -g generator-angular install angular scaffolding
      - run: bower install
#      - run: sudo apt-get install ruby-dev
      - run: sudo apt-get install rubygems
      - run: sudo apt-get install rubygems-integration
      - run: sudo apt-get install ruby-dev
      - run: sudo apt-get install ruby-all-dev
#      - run: sudo gem install compass
      - run: sudo gem install --no-rdoc --no-ri sass -v 3.4.22
      - run: sudo gem install --no-rdoc --no-ri compass
      - run: sudo grunt build --force

      - deploy:
          name: deploy-to-dev
          command: |
            echo ${CIRCLE_BRANCH}
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              chmod 400 bin/moveup-dev-tokyo.pem &&
              zip -r dist.zip ./dist/ &&
              scp -o StrictHostKeyChecking=no -i bin/moveup-dev-tokyo.pem  /home/circleci/repo/dist.zip ec2-user@13.230.169.165:/tmp/ &&
              ssh -o StrictHostKeyChecking=no -i bin/moveup-dev-tokyo.pem ec2-user@13.230.169.165 sudo rm -rf /usr/share/nginx/html/* &&
              ssh -o StrictHostKeyChecking=no -i bin/moveup-dev-tokyo.pem ec2-user@13.230.169.165 sudo unzip -o /tmp/dist.zip -d /usr/share/nginx/ &&
              ssh -o StrictHostKeyChecking=no -i bin/moveup-dev-tokyo.pem ec2-user@13.230.169.165 sudo rm -rf /usr/share/nginx/html/ &&
              ssh -o StrictHostKeyChecking=no -i bin/moveup-dev-tokyo.pem ec2-user@13.230.169.165 sudo mv /usr/share/nginx/dist/ /usr/share/nginx/html/
            fi


